### ISSUE TITLE
wss web socket creation issue

### ISSUE THREAD

**Issue by prakashkolandaivelu** [elabs/mobile-websocket-example#10]
I got - closed connection -1 , draft org.java_websocket.drafts.Draft_17@75599672 refuses handshake , false - then changed the code as below:
Socket creation coode
    webClient = new APICWebClient(new URI(getWebSocketUrl(currentApic.IPAddress, port)), new Draft_17());
                webClient.connect();

Constructor:
    public APICWebClient(URI serverURI, Draft draft) {
        super(serverURI, draft);

```
    SSLContext sslContext = null;
    try {
        sslContext = SSLContext.getDefault();
    } catch (NoSuchAlgorithmException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));
    logger.info("Socket object created");
}
```

Draft_17. I get : closed connection -1 , , true. Any help here. This happens during socket creation.

**Comment by aniruddhambarkar** [comment]
Facing same issue for WSS.. tried setting SSL context but still same issue

**Comment by prakashkolandaivelu** [comment]
super(serverURI, draft);
        SSLContext sslContext;
        try {
            sslContext = SSLContext.getInstance("SSL");
            // set up a TrustManager that trusts everything
            sslContext.init(null, new TrustManager[] { new X509TrustManager() {
                public X509Certificate[] getAcceptedIssuers() {
                    logger.debug("getAcceptedIssuers =============");
                    return null;
                }

                public void checkClientTrusted(X509Certificate[] certs, String authType) {
                    logger.debug("checkClientTrusted =============");
                }

                public void checkServerTrusted(X509Certificate[] certs, String authType) {
                    logger.debug("checkServerTrusted =============");
                }
            } }, new SecureRandom());
            this.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));
            this.messageHandlerList = messageHandlerList;
        } catch (Exception e) {
            logger.error("Error while creating the Socket object {}");
        }
        logger.debug("Socket object created");
I changed the Constructor something like this to make it work.
