### ISSUE TITLE
Android client Garbage collector issue

### ISSUE THREAD

**Issue by szczepaan** [elabs/mobile-websocket-example#4]
on android when i move to another activity and i finish activity with 
<pre>	private WebSocketClient mWebSocketClient;
</pre>
I see in logcat going mad message every 10 ms
<pre>
GC_FOR_ALLOC freed 512K, 4% free 17338K/17896K, paused 13ms, total 13ms
</pre>
how to propertly close websocket client and alla associated resources ?
I do
<pre> mWebSocketClient.close(); </pre>
but apparently it is not sufficient

when I set up the client I also use code
<pre>
SSLContext sslContext = null;
		try {
			sslContext = SSLContext.getInstance("TLS");
			sslContext.init(null, null, null); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch (KeyManagementException e) {
			e.printStackTrace();
		}
//
		mWebSocketClient.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));
</pre>
maybe that has to do with it,
also when I tried to investigate what's allocated I found it was about

<pre>
AllocatedClass javax.net.ssl.SSLEngineResult	
Allocated in org.apache.harmony.xnet.provider.jsse.SSLEngineImpl	unwrap	
</pre>

any help?

**Comment by ankor** [comment]
This seems to be related to SSL handling, which is not covered in the Android example in this repository. I see you raised the same issue in the Java-WebSocket repo as well and maybe they can help.
