### ISSUE TITLE
Android 5.0 Lollipop wss stopped working 

### ISSUE THREAD

**Issue by szczepaan** [elabs/mobile-websocket-example#6]
Hey,

below code worked for Android 4.x.x (also Kitkat), and stopped working on Lollipop

<pre>
SSLContext sslContext = null;
		try {
			sslContext = SSLContext.getInstance("TLS");
			sslContext.init(null, null, null); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch (KeyManagementException e) {
			e.printStackTrace();
		}
		mWebSocketClient.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));

mWebSocketClient.connect();
</pre>

I dont get any error, it just doesnt connect to wss server, onOpen() is never called :/

Please help

**Comment by ankor** [comment]
The example code for Android in this repository does not handle SSL at all, but for anyone interested I see you raised this issue in the Java-WebSockets repo as well and there is some more info: https://github.com/TooTallNate/Java-WebSocket/issues/293
